global:
  postgresql:
    secrets: front-app-postgresql

image:
  repository: lwplapbs/back
  tag:  "latest"
  pullPolicy: Always


appconfig: |-
  server.port: 8080
  ################### Kafka ##############################
  spring:
    kafka:
      bootstrap-servers:  "front-app-kafka-headless.default.svc.cluster.local:9093"
      consumer:
        group-id: "back-group-local"
    datasource.url: jdbc:postgresql://front-app-postgresql:5432/postgres
    datasource.username: postgres
  management.server.port: 8081
